### ISSUE TITLE
Basic usage?

### ISSUE THREAD

**Issue by gamesbook** [mjwestcott/fennel#2]
I am not sure if my expectations are correct here.

The docs say: 
_You have some work that needs to happen (e.g. generating image thumbnails, sending an email), but you don’t want the user to wait for it to complete before returning a response. In this case, it’s important that the task succeeds, but your code will not be waiting to ensure that it does._

My simple code snippet looks as follows:

```
import time
from fennel import App
from fennel.client import gather

app = App(name='myapp', redis_url='redis://127.0.0.1:6379')

@app.task(retries=3)
def foo(n):
    print(f'sleeping {n}')
    time.sleep(n)

if __name__ == '__main__':
    print(int(time.time()))
    foo(2)
    print(int(time.time()))
    foo(4)
    print(int(time.time()))
    foo(6)
    print(int(time.time()))
    print('done')
```

My expectation would be that each of the instances of `foo` are set to run as tasks and therefore there should be no delay at all between each call.  However, the calling code clearly waits for each instance to run to completion before the next call.

```
2020-07-29T09:37:10.257801Z     DEBUG found-task        pid=2170 name=__main__.foo 
1596015430
sleeping 2
1596015432
sleeping 4
1596015436
sleeping 6
1596015442
done
```

What needs to happen to get the code to run as expected (zero delays)?

**Comment by mjwestcott** [comment]
Hi, the short answer is that you need to use `foo.delay(2)`

For convenience we decorate your functions and allow you call them as normal via `foo(2)`. But to use them as Fennel tasks you need to enqueue them for background processing via `foo.delay(2)`. You'll also need to run the worker so that tasks are taken off the queue and processed. Have a look at the docs here: https://fennel.readthedocs.io/en/latest/reference.html#fennel.App.task

**Comment by gamesbook** [comment]
Thanks.
